name: Pushes Latency Check

on:
  push:
    branches:
      master

jobs:
  timer:
    runs-on: ubuntu-latest
    steps:
      - uses: jakejarvis/wait-action@master
        with:
          time: '10s'

  release:
    runs-on: ubuntu-latest
    needs: timer
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Native git hash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git rev-parse --short HEAD
      - name: GitHub sha hash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sha_hash:  ${{ github.sha }}
        run: echo github hash = $sha_hash
